### ISSUE TITLE
test_get_pair_by_index_not_found fails

### ISSUE THREAD

**Issue by ml31415** [nosofa/uniswap-v2-py#10]
To my understanding, one of the test cases is failing due to improper error handling within `web3`. The `ValueError` should be caught there and throw a `BadFunctionCallOutput` instead. There is nothing to be done here for this project, I'm just creating this issue for reference.
```
ERROR: test_get_pair_by_index_not_found (tests.test.UniswapV2ClientTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/travis/build/asynctomatic/uniswap-v2-py/tests/test.py", line 91, in test_get_pair_by_index_not_found
    pair = self.uniswap.get_pair_by_index(99999)
  File "/home/travis/build/asynctomatic/uniswap-v2-py/uniswap/uniswap.py", line 205, in get_pair_by_index
    return self.contract.functions.allPairs(pair_index).call()
  File "/home/travis/virtualenv/python3.6.7/lib/python3.6/site-packages/web3/contract.py", line 959, in call
    **self.kwargs
  File "/home/travis/virtualenv/python3.6.7/lib/python3.6/site-packages/web3/contract.py", line 1490, in call_contract_function
    return_data = web3.eth.call(call_transaction, block_identifier=block_id)
  File "/home/travis/virtualenv/python3.6.7/lib/python3.6/site-packages/eth_utils/functional.py", line 45, in inner
    return callback(fn(*args, **kwargs))
  File "/home/travis/virtualenv/python3.6.7/lib/python3.6/site-packages/web3/eth.py", line 430, in call
    [transaction, block_identifier],
  File "/home/travis/virtualenv/python3.6.7/lib/python3.6/site-packages/web3/manager.py", line 153, in request_blocking
    raise ValueError(response["error"])
ValueError: {'code': -32000, 'message': 'invalid opcode: opcode 0xfe not defined'}`
```

**Comment by kclowes** [comment]
FWIW, I don't think this is an issue with Web3 error handling. It looks like the invalid opcode was triggered, which usually comes from an `assert` in your contract code. `BadFunctionCallOutput` should only be raised when web3py can't decode the output, which most likely means there is an ABI mismatch.
